### PR TITLE
Upgrade howler.js to fix bug in Safari

### PR DESCRIPTION
**Pull request by jjhamshaw**
To reproduce the bug:

- add a `.wav` file to the examples (I have added a file if you want to leave it in)
- run one of the example pages in this repo with Safari (v14)
- throws error

Fix:
Upgrading howler version fixes this - see: https://github.com/goldfire/howler.js/pull/1415

### CODE REVIEW

**Comment by E-Kuerschner** [comment]
Fixes #54

**Comment by E-Kuerschner** [comment]
Thanks for the PR @jjhamshaw! Could you make sure the yarn.lock file gets updated with the upgrade?

**Comment by jjhamshaw** [comment]
🤦 sure, will update now...

**Review by E-Kuerschner — APPROVED** [review]

**Comment by E-Kuerschner** [comment]
@jjhamshaw its now available in v1.2.3

**Comment by jjhamshaw** [comment]
Brilliant, thanks @E-Kuerschner!

**Pull request merged**
